services:
  database:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: eshop
      POSTGRES_DB: eshop
    ports:
      - '5433:5432'
    volumes:
      - ./docker/postgres-init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - '9081:8080'

 
